# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Master PR
on: 
  pull_request:
    branches:
      - "main"

jobs:
  Jira:
    runs-on: ubuntu-latest
    permissions:
      issues: write # needed to label/comment on the PR
      pull-requests: write # labels on a PR require this in addition to issues:write
    steps:
    # https://github.com/capacity-autoqa/jira-lint/tree/0.2.0
    - uses: capacity-autoqa/jira-lint@cc8ccdafcbe10be85e2bf91d5587f4f84dbe82aa
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        jira-token: ${{ secrets.JIRA_TOKEN }}
        jira-base-url: ${{ vars.JIRA_ENDPOINT }}
        skip-branches: '^snyk-fix-'
        skip-comments: true
        pr-threshold: 1000
        allowed_issue_statuses: ${{ vars.JIRA_ALLOWED_STATUSES || 'Open,Reopened,To Do,In Progress' }}
        validate_issue_status: true
