# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Master PR
on: 
  pull_request:
    branches:
      - "master"

jobs:
  Jira:
    runs-on: ubuntu-latest
    steps:
    - uses: CollabIP/jira-lint@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        jira-token: ${{ secrets.JIRA_TOKEN }}
        jira-base-url: https://creovai.atlassian.net
        skip-comments: true
        pr-threshold: 1000
        allowed_issue_statuses: "In Progress,Done,READY FOR SIGN-OFF"
        validate_issue_status: true
